### ISSUE TITLE
Building JavaFX applications = cannot find symbol -> wrong Java 8 version?

### ISSUE THREAD

**Issue by stevenschwenke** [Shippable/support#1649]
My Maven project located at https://github.com/stevenschwenke/Java8Workshop fails to build because
<code>
[ERROR] COMPILATION ERROR : [INFO] ------------------------------------------------------------- [ERROR] /home/shippable/workspace/src/github.com/stevenschwenke/Java8Workshop/src/test/java/de/stevenschwenke/java/java8workshop/C_09_JavaFX.java:[193,13] cannot find symbol symbol: class Alert location: class de.stevenschwenke.java.java8workshop.C_09_JavaFX [ERROR] /home/shippable/workspace/src/github.com/stevenschwenke/Java8Workshop/src/test/java/de/stevenschwenke/java/java8workshop/C_09_JavaFX.java:[193,31] cannot find symbol symbol: class Alert location: class de.stevenschwenke.java.java8workshop.C_09_JavaFX [ERROR] /home/shippable/workspace/src/github.com/stevenschwenke/Java8Workshop/src/test/java/de/stevenschwenke/java/java8workshop/C_09_JavaFX.java:[193,42] package Alert does not exist [INFO] 3 errors [INFO] ------------------------------------------------------------- [INFO] ------------------------------------------------------------------------ [INFO] BUILD FAILURE 
</code>

In my yml-file, I set language: java and jdk: oraclejdk8.

I think the issue is that a JDK < Java 1.8u40 is used for this build. If so, using a newer version probably solves this issue. Local build with 1.8u45 is fine. How can I set this version in the yml file?

Thanks for your work and keep up the good stuff! :)

**Comment by stevenschwenke** [comment]
TravisCI is getting the same error on this repository.

**Comment by stevenschwenke** [comment]
There's a configuration in travis where you can set a new JDK, see https://github.com/travis-ci/travis-ci/issues/4042#issuecomment-109756980

Worked for me.

**Comment by lekhab** [comment]
@stevenschwenke: glad you were able to work it out using the travis setting :-)

FYI - The shippable custom image for java: shippableimages/ubuntu1204_java is also now updated to 1.8.0_45 and I could run a fork of your project successfully with that image. 

Under project settings, set your build image to ```shippableimages/ubuntu1204_java```

Since it is a custom image and does not add any services, need to add a few more lines. The YML that worked for me is below. We need to explicitly define the JDK version by using the $SHIPPABLE_JDK_VERSION  in before_script for custom images, since we don't change versions during builds. 

```
# language
language: java

# version numbers
jdk:
    - oraclejdk8
    
before_install:
   - apt-get update
   - apt-get install -y maven
   
before_script:
   - if [[ $SHIPPABLE_JDK_VERSION == "oraclejdk8" ]] ; then export JAVA_HOME="/usr/lib/jvm/java-8-oracle"; export PATH="$PATH:/usr/lib/jvm/java-8-oracle/bin"; export java_path="/usr/lib/jvm/java-8-oracle/jre/bin/java"; fi
   - update-alternatives --set java $java_path
   - java -version

after_success:
   - mvn clean cobertura:cobertura
   - mvn test
```

We recommend custom images since they are a lot more lightweight compared to the default shippable/minv2 image that is huge and installs practically everything, so a lot harder to keep it updated.  we eventually plan to deprecate this in favor of lighter, more custom images.

Please let me know if the YML and custom build_image works for you.

**Comment by manishas** [comment]
This is an old issue and looks like it had a resolution. closing.
